### ISSUE TITLE
把 cloudflare 承载网站都解析到固定几个 IP 上去？

### ISSUE THREAD

**Issue by zz5678** [zhiyi7/gfw-pac#21]
https://github.com/felixonmars/dnsmasq-china-list/issues/345
https://github.com/badafans/better-cloudflare-ip/issues/56
这里过来的讨论。

一直是在手动作这事儿，效果很好

**Comment by zhiyi7** [comment]
通过这个项目生成的pac规则是，没在名单里的国外ip都通过代理访问。指定到固定ip会因为不是最近节点而让访问速度变慢，还会产生因为维护同步不及时导致访问出错。完全没有必要。
