### ISSUE TITLE
缺chatgpt 域名

### ISSUE THREAD

**Issue by xypku** [zhiyi7/gfw-pac#28]
chatgpt 域名不在列表中 要手动敞添加才能正常访问

**Comment by zhiyi7** [comment]
<img width="416" alt="截屏2024-10-05 00 16 42" src="https://github.com/user-attachments/assets/2b4cb40c-9a3c-4726-9b82-34247dc956d8">
解析后不会命中任何规则，会返回代理。如果你的域名解析匹配到了中国IP，建议更换DNS或者手工加入代理域名列表。
