### ISSUE TITLE
IPv6 只需前64

### ISSUE THREAD

**Issue by NewFuture** [zhiyi7/gfw-pac#32]
在大的CIDR中IPv6的掩码长度不超过64位，对于ipv6的比较和转换，只需前64位即可

**Comment by NewFuture** [comment]
ipv4 也只需要前24位

**Comment by NewFuture** [comment]
ipvv6在ipToBinary的时候其实只需截取前64位的结果，在ipTobinary里只需要处理前64位

**Comment by zhiyi7** [comment]
> ipvv6在ipToBinary的时候其实只需截取前64位的结果，在ipTobinary里只需要处理前64位

这么做的意义是什么？

**Comment by zhiyi7** [comment]
commit 74e6d0aa477699f90ea22bfda9c271f0f8a9c9a5 生成的文件中也改为了只保留了前缀位
