### ISSUE TITLE
定义多个代理 ？

### ISSUE THREAD

**Issue by ayasechan** [zhiyi7/gfw-pac#6]
想针对不同的域名使用不同的代理是否有办法实现呢

**Comment by guoshuhuang** [comment]
同问

**Comment by Rayleign** [comment]
修改模板文件，定义多个domainsUsingProxy(如domainsUsingProxy1、domainsUsingProxy2)和多个proxy(如proxy1、proxy2)变量，域名匹配到哪个domainsUsingProxy就走哪个proxy;

然后再修改gfw-pac.py，接收--user-rule和多个proxy
