### ISSUE TITLE
建议把 print 改成函数

### ISSUE THREAD

**Issue by madobet** [zhiyi7/gfw-pac#7]
![screenshot](https://user-images.githubusercontent.com/51693231/75607735-27f54080-5b35-11ea-9c60-0c025fcc16b5.png)

**Comment by zhiyi7** [comment]
切换到python2试试。

**Comment by madobet** [comment]
> 切换到python2试试。

我知道这是 Python2 的语法，我的意思是毕竟 Python2 停止维护了，这个项目代码也不多，不如稍微改写一下迁移到 Python3

**Comment by zhiyi7** [comment]
ported to python3 by @grandpaul
